# redirect all other traffic from port 80 (http) to port 443 (https)
server {
    listen 80;
    listen [::]:80;
    server_name fdp.example.com;
    return 301 https://$host$request_uri;
}

# pass traffic from port 443 to the upstream web server, on the docker network
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name fdp.example.com;
    ssl_certificate /etc/letsencrypt/live/fdp.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fdp.example.com/privkey.pem;

    location / {
        proxy_pass http://fdp-client:80;
        proxy_http_version  1.1;
        proxy_set_header    Host                $host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto   $scheme;
    }
}

# catch all remaining traffic
server {
    listen       80 default_server;
    listen  [::]:80 default_server;
    listen       443 ssl default_server;
    listen  [::]:443 ssl default_server;
    ssl_reject_handshake on;
    server_name  _;  # match none
    return       444;
}
